export const GAME_CONFIG = {
    DISTANT_PIPES_FROM_START_POINT : 300,
    DISTANT_BETWEEN_PIPES : 180,
    MAX_PIPE_POS_Y : 90,
    MIN_PIPE_POS_Y : -90,
    PIPES_POOL_COUNT : 10,
    PIPE_MOVE_SPEED : -100,
    BIRD_JUMP_SPEED : 180,
    BIRD_DECREASE_SPEED: 12,
}